// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.yu.protobuf.object;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  java.util.List<com.yu.protobuf.object.Person> 
      getPeopleList();
  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  com.yu.protobuf.object.Person getPeople(int index);
  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  java.util.List<? extends com.yu.protobuf.object.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  com.yu.protobuf.object.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
